name: bmi_cal_new
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  velocity_x: ^4.2.1
  syncfusion_flutter_sliders: ^26.2.11
  flutter_svg: ^2.0.4
  percent_indicator: ^4.2.3
  flutter_launcher_icons: ^0.13.1
  iconsax: ^0.0.8
  carousel_slider: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/men_chart/
    - assets/images/women_chart/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
